name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Python 3.11
      uses:  actions/setup-python@v5
      with:
        python-version: '3.11.7'

    - name: Install Poetry
      uses: snok/install-poetry@v1  # Install Poetry

    - name: Install dependencies
      run: |
        poetry install --no-dev  # Install dependencies without dev ones

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

  tests:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
    - uses: actions/checkout@v3

    - name: Run integration tests (pull request only)
      if: ${{ github.event.type == 'pull_request' }}
      run: |
        poetry install --with dev  # Install dev dependencies
        docker-compose up -d  # Start services in detached mode
        poetry run pytest --cov-report term-missing --cov=src tests/  # Run integration tests




