name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
      
    - name: Install Poetry
      uses: snok/install-poetry@v1  # Install Poetry

    - name: Install dependencies
      run: |
        poetry install --no-dev  # Install dependencies without dev ones
  
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3  # Use the pre-commit action
      with:
        fail_fast: true           # Continue even if some hooks fail
  
  tests:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
    - uses: actions/checkout@v3

    - name: Run integration tests (pull request only)
      if: ${{ github.event.type == 'pull_request' }}
      run: |
        poetry install --with dev  # Install dev dependencies
        docker-compose up -d  # Start services in detached mode
        poetry run pytest --cov-report term-missing --cov=src tests/  # Run integration tests



          
